//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeptAuthUAT
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeptAuthUAT.Dept_AuthenticationSoap")]
    public interface Dept_AuthenticationSoap
    {
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParameter", ReplyAction="*")]
        DeptAuthUAT.GetParameterResponse GetParameter(DeptAuthUAT.GetParameterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParameter", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.GetParameterResponse> GetParameterAsync(DeptAuthUAT.GetParameterRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParameterNew", ReplyAction="*")]
        DeptAuthUAT.GetParameterNewResponse GetParameterNew(DeptAuthUAT.GetParameterNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParameterNew", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.GetParameterNewResponse> GetParameterNewAsync(DeptAuthUAT.GetParameterNewRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceParameter", ReplyAction="*")]
        DeptAuthUAT.GetServiceParameterResponse GetServiceParameter(DeptAuthUAT.GetServiceParameterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceParameter", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.GetServiceParameterResponse> GetServiceParameterAsync(DeptAuthUAT.GetServiceParameterRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAppStatus", ReplyAction="*")]
        DeptAuthUAT.SetAppStatusResponse SetAppStatus(DeptAuthUAT.SetAppStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAppStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.SetAppStatusResponse> SetAppStatusAsync(DeptAuthUAT.SetAppStatusRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAppeal", ReplyAction="*")]
        DeptAuthUAT.InsertAppealResponse InsertAppeal(DeptAuthUAT.InsertAppealRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAppeal", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.InsertAppealResponse> InsertAppealAsync(DeptAuthUAT.InsertAppealRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAppealHearingDate", ReplyAction="*")]
        DeptAuthUAT.UpdateAppealHearingDateResponse UpdateAppealHearingDate(DeptAuthUAT.UpdateAppealHearingDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAppealHearingDate", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.UpdateAppealHearingDateResponse> UpdateAppealHearingDateAsync(DeptAuthUAT.UpdateAppealHearingDateRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAppealDecision", ReplyAction="*")]
        DeptAuthUAT.UpdateAppealDecisionResponse UpdateAppealDecision(DeptAuthUAT.UpdateAppealDecisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAppealDecision", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.UpdateAppealDecisionResponse> UpdateAppealDecisionAsync(DeptAuthUAT.UpdateAppealDecisionRequest request);
        
        // CODEGEN: Generating message contract since element name Str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStringData", ReplyAction="*")]
        DeptAuthUAT.GetStringDataResponse GetStringData(DeptAuthUAT.GetStringDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStringData", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.GetStringDataResponse> GetStringDataAsync(DeptAuthUAT.GetStringDataRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AaplesarkarPay", ReplyAction="*")]
        DeptAuthUAT.AaplesarkarPayResponse AaplesarkarPay(DeptAuthUAT.AaplesarkarPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AaplesarkarPay", ReplyAction="*")]
        System.Threading.Tasks.Task<DeptAuthUAT.AaplesarkarPayResponse> AaplesarkarPayAsync(DeptAuthUAT.AaplesarkarPayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParameterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParameter", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.GetParameterRequestBody Body;
        
        public GetParameterRequest()
        {
        }
        
        public GetParameterRequest(DeptAuthUAT.GetParameterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParameterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public GetParameterRequestBody()
        {
        }
        
        public GetParameterRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParameterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParameterResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.GetParameterResponseBody Body;
        
        public GetParameterResponse()
        {
        }
        
        public GetParameterResponse(DeptAuthUAT.GetParameterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParameterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetParameterResult;
        
        public GetParameterResponseBody()
        {
        }
        
        public GetParameterResponseBody(string GetParameterResult)
        {
            this.GetParameterResult = GetParameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParameterNewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParameterNew", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.GetParameterNewRequestBody Body;
        
        public GetParameterNewRequest()
        {
        }
        
        public GetParameterNewRequest(DeptAuthUAT.GetParameterNewRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParameterNewRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public GetParameterNewRequestBody()
        {
        }
        
        public GetParameterNewRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParameterNewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParameterNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.GetParameterNewResponseBody Body;
        
        public GetParameterNewResponse()
        {
        }
        
        public GetParameterNewResponse(DeptAuthUAT.GetParameterNewResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParameterNewResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetParameterNewResult;
        
        public GetParameterNewResponseBody()
        {
        }
        
        public GetParameterNewResponseBody(string GetParameterNewResult)
        {
            this.GetParameterNewResult = GetParameterNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceParameterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceParameter", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.GetServiceParameterRequestBody Body;
        
        public GetServiceParameterRequest()
        {
        }
        
        public GetServiceParameterRequest(DeptAuthUAT.GetServiceParameterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServiceParameterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public GetServiceParameterRequestBody()
        {
        }
        
        public GetServiceParameterRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceParameterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceParameterResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.GetServiceParameterResponseBody Body;
        
        public GetServiceParameterResponse()
        {
        }
        
        public GetServiceParameterResponse(DeptAuthUAT.GetServiceParameterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServiceParameterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetServiceParameterResult;
        
        public GetServiceParameterResponseBody()
        {
        }
        
        public GetServiceParameterResponseBody(string GetServiceParameterResult)
        {
            this.GetServiceParameterResult = GetServiceParameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAppStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAppStatus", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.SetAppStatusRequestBody Body;
        
        public SetAppStatusRequest()
        {
        }
        
        public SetAppStatusRequest(DeptAuthUAT.SetAppStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAppStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public SetAppStatusRequestBody()
        {
        }
        
        public SetAppStatusRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAppStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAppStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.SetAppStatusResponseBody Body;
        
        public SetAppStatusResponse()
        {
        }
        
        public SetAppStatusResponse(DeptAuthUAT.SetAppStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAppStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetAppStatusResult;
        
        public SetAppStatusResponseBody()
        {
        }
        
        public SetAppStatusResponseBody(string SetAppStatusResult)
        {
            this.SetAppStatusResult = SetAppStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAppealRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAppeal", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.InsertAppealRequestBody Body;
        
        public InsertAppealRequest()
        {
        }
        
        public InsertAppealRequest(DeptAuthUAT.InsertAppealRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAppealRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public InsertAppealRequestBody()
        {
        }
        
        public InsertAppealRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAppealResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAppealResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.InsertAppealResponseBody Body;
        
        public InsertAppealResponse()
        {
        }
        
        public InsertAppealResponse(DeptAuthUAT.InsertAppealResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAppealResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertAppealResult;
        
        public InsertAppealResponseBody()
        {
        }
        
        public InsertAppealResponseBody(string InsertAppealResult)
        {
            this.InsertAppealResult = InsertAppealResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAppealHearingDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAppealHearingDate", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.UpdateAppealHearingDateRequestBody Body;
        
        public UpdateAppealHearingDateRequest()
        {
        }
        
        public UpdateAppealHearingDateRequest(DeptAuthUAT.UpdateAppealHearingDateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAppealHearingDateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public UpdateAppealHearingDateRequestBody()
        {
        }
        
        public UpdateAppealHearingDateRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAppealHearingDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAppealHearingDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.UpdateAppealHearingDateResponseBody Body;
        
        public UpdateAppealHearingDateResponse()
        {
        }
        
        public UpdateAppealHearingDateResponse(DeptAuthUAT.UpdateAppealHearingDateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAppealHearingDateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAppealHearingDateResult;
        
        public UpdateAppealHearingDateResponseBody()
        {
        }
        
        public UpdateAppealHearingDateResponseBody(string UpdateAppealHearingDateResult)
        {
            this.UpdateAppealHearingDateResult = UpdateAppealHearingDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAppealDecisionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAppealDecision", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.UpdateAppealDecisionRequestBody Body;
        
        public UpdateAppealDecisionRequest()
        {
        }
        
        public UpdateAppealDecisionRequest(DeptAuthUAT.UpdateAppealDecisionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAppealDecisionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public UpdateAppealDecisionRequestBody()
        {
        }
        
        public UpdateAppealDecisionRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAppealDecisionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAppealDecisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.UpdateAppealDecisionResponseBody Body;
        
        public UpdateAppealDecisionResponse()
        {
        }
        
        public UpdateAppealDecisionResponse(DeptAuthUAT.UpdateAppealDecisionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAppealDecisionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAppealDecisionResult;
        
        public UpdateAppealDecisionResponseBody()
        {
        }
        
        public UpdateAppealDecisionResponseBody(string UpdateAppealDecisionResult)
        {
            this.UpdateAppealDecisionResult = UpdateAppealDecisionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStringDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStringData", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.GetStringDataRequestBody Body;
        
        public GetStringDataRequest()
        {
        }
        
        public GetStringDataRequest(DeptAuthUAT.GetStringDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStringDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Str;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Actioncode;
        
        public GetStringDataRequestBody()
        {
        }
        
        public GetStringDataRequestBody(string Str, string DeptCode, int Actioncode)
        {
            this.Str = Str;
            this.DeptCode = DeptCode;
            this.Actioncode = Actioncode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStringDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStringDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.GetStringDataResponseBody Body;
        
        public GetStringDataResponse()
        {
        }
        
        public GetStringDataResponse(DeptAuthUAT.GetStringDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStringDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStringDataResult;
        
        public GetStringDataResponseBody()
        {
        }
        
        public GetStringDataResponseBody(string GetStringDataResult)
        {
            this.GetStringDataResult = GetStringDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AaplesarkarPayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AaplesarkarPay", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.AaplesarkarPayRequestBody Body;
        
        public AaplesarkarPayRequest()
        {
        }
        
        public AaplesarkarPayRequest(DeptAuthUAT.AaplesarkarPayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AaplesarkarPayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public AaplesarkarPayRequestBody()
        {
        }
        
        public AaplesarkarPayRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AaplesarkarPayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AaplesarkarPayResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeptAuthUAT.AaplesarkarPayResponseBody Body;
        
        public AaplesarkarPayResponse()
        {
        }
        
        public AaplesarkarPayResponse(DeptAuthUAT.AaplesarkarPayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AaplesarkarPayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AaplesarkarPayResult;
        
        public AaplesarkarPayResponseBody()
        {
        }
        
        public AaplesarkarPayResponseBody(string AaplesarkarPayResult)
        {
            this.AaplesarkarPayResult = AaplesarkarPayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface Dept_AuthenticationSoapChannel : DeptAuthUAT.Dept_AuthenticationSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Dept_AuthenticationSoapClient : System.ServiceModel.ClientBase<DeptAuthUAT.Dept_AuthenticationSoap>, DeptAuthUAT.Dept_AuthenticationSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Dept_AuthenticationSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Dept_AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), Dept_AuthenticationSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Dept_AuthenticationSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Dept_AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Dept_AuthenticationSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Dept_AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Dept_AuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.GetParameterResponse DeptAuthUAT.Dept_AuthenticationSoap.GetParameter(DeptAuthUAT.GetParameterRequest request)
        {
            return base.Channel.GetParameter(request);
        }
        
        public string GetParameter(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.GetParameterRequest inValue = new DeptAuthUAT.GetParameterRequest();
            inValue.Body = new DeptAuthUAT.GetParameterRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DeptAuthUAT.GetParameterResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).GetParameter(inValue);
            return retVal.Body.GetParameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.GetParameterResponse> DeptAuthUAT.Dept_AuthenticationSoap.GetParameterAsync(DeptAuthUAT.GetParameterRequest request)
        {
            return base.Channel.GetParameterAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.GetParameterResponse> GetParameterAsync(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.GetParameterRequest inValue = new DeptAuthUAT.GetParameterRequest();
            inValue.Body = new DeptAuthUAT.GetParameterRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).GetParameterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.GetParameterNewResponse DeptAuthUAT.Dept_AuthenticationSoap.GetParameterNew(DeptAuthUAT.GetParameterNewRequest request)
        {
            return base.Channel.GetParameterNew(request);
        }
        
        public string GetParameterNew(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.GetParameterNewRequest inValue = new DeptAuthUAT.GetParameterNewRequest();
            inValue.Body = new DeptAuthUAT.GetParameterNewRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DeptAuthUAT.GetParameterNewResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).GetParameterNew(inValue);
            return retVal.Body.GetParameterNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.GetParameterNewResponse> DeptAuthUAT.Dept_AuthenticationSoap.GetParameterNewAsync(DeptAuthUAT.GetParameterNewRequest request)
        {
            return base.Channel.GetParameterNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.GetParameterNewResponse> GetParameterNewAsync(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.GetParameterNewRequest inValue = new DeptAuthUAT.GetParameterNewRequest();
            inValue.Body = new DeptAuthUAT.GetParameterNewRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).GetParameterNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.GetServiceParameterResponse DeptAuthUAT.Dept_AuthenticationSoap.GetServiceParameter(DeptAuthUAT.GetServiceParameterRequest request)
        {
            return base.Channel.GetServiceParameter(request);
        }
        
        public string GetServiceParameter(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.GetServiceParameterRequest inValue = new DeptAuthUAT.GetServiceParameterRequest();
            inValue.Body = new DeptAuthUAT.GetServiceParameterRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DeptAuthUAT.GetServiceParameterResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).GetServiceParameter(inValue);
            return retVal.Body.GetServiceParameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.GetServiceParameterResponse> DeptAuthUAT.Dept_AuthenticationSoap.GetServiceParameterAsync(DeptAuthUAT.GetServiceParameterRequest request)
        {
            return base.Channel.GetServiceParameterAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.GetServiceParameterResponse> GetServiceParameterAsync(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.GetServiceParameterRequest inValue = new DeptAuthUAT.GetServiceParameterRequest();
            inValue.Body = new DeptAuthUAT.GetServiceParameterRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).GetServiceParameterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.SetAppStatusResponse DeptAuthUAT.Dept_AuthenticationSoap.SetAppStatus(DeptAuthUAT.SetAppStatusRequest request)
        {
            return base.Channel.SetAppStatus(request);
        }
        
        public string SetAppStatus(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.SetAppStatusRequest inValue = new DeptAuthUAT.SetAppStatusRequest();
            inValue.Body = new DeptAuthUAT.SetAppStatusRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DeptAuthUAT.SetAppStatusResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).SetAppStatus(inValue);
            return retVal.Body.SetAppStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.SetAppStatusResponse> DeptAuthUAT.Dept_AuthenticationSoap.SetAppStatusAsync(DeptAuthUAT.SetAppStatusRequest request)
        {
            return base.Channel.SetAppStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.SetAppStatusResponse> SetAppStatusAsync(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.SetAppStatusRequest inValue = new DeptAuthUAT.SetAppStatusRequest();
            inValue.Body = new DeptAuthUAT.SetAppStatusRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).SetAppStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.InsertAppealResponse DeptAuthUAT.Dept_AuthenticationSoap.InsertAppeal(DeptAuthUAT.InsertAppealRequest request)
        {
            return base.Channel.InsertAppeal(request);
        }
        
        public string InsertAppeal(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.InsertAppealRequest inValue = new DeptAuthUAT.InsertAppealRequest();
            inValue.Body = new DeptAuthUAT.InsertAppealRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DeptAuthUAT.InsertAppealResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).InsertAppeal(inValue);
            return retVal.Body.InsertAppealResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.InsertAppealResponse> DeptAuthUAT.Dept_AuthenticationSoap.InsertAppealAsync(DeptAuthUAT.InsertAppealRequest request)
        {
            return base.Channel.InsertAppealAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.InsertAppealResponse> InsertAppealAsync(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.InsertAppealRequest inValue = new DeptAuthUAT.InsertAppealRequest();
            inValue.Body = new DeptAuthUAT.InsertAppealRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).InsertAppealAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.UpdateAppealHearingDateResponse DeptAuthUAT.Dept_AuthenticationSoap.UpdateAppealHearingDate(DeptAuthUAT.UpdateAppealHearingDateRequest request)
        {
            return base.Channel.UpdateAppealHearingDate(request);
        }
        
        public string UpdateAppealHearingDate(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.UpdateAppealHearingDateRequest inValue = new DeptAuthUAT.UpdateAppealHearingDateRequest();
            inValue.Body = new DeptAuthUAT.UpdateAppealHearingDateRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DeptAuthUAT.UpdateAppealHearingDateResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).UpdateAppealHearingDate(inValue);
            return retVal.Body.UpdateAppealHearingDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.UpdateAppealHearingDateResponse> DeptAuthUAT.Dept_AuthenticationSoap.UpdateAppealHearingDateAsync(DeptAuthUAT.UpdateAppealHearingDateRequest request)
        {
            return base.Channel.UpdateAppealHearingDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.UpdateAppealHearingDateResponse> UpdateAppealHearingDateAsync(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.UpdateAppealHearingDateRequest inValue = new DeptAuthUAT.UpdateAppealHearingDateRequest();
            inValue.Body = new DeptAuthUAT.UpdateAppealHearingDateRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).UpdateAppealHearingDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.UpdateAppealDecisionResponse DeptAuthUAT.Dept_AuthenticationSoap.UpdateAppealDecision(DeptAuthUAT.UpdateAppealDecisionRequest request)
        {
            return base.Channel.UpdateAppealDecision(request);
        }
        
        public string UpdateAppealDecision(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.UpdateAppealDecisionRequest inValue = new DeptAuthUAT.UpdateAppealDecisionRequest();
            inValue.Body = new DeptAuthUAT.UpdateAppealDecisionRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DeptAuthUAT.UpdateAppealDecisionResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).UpdateAppealDecision(inValue);
            return retVal.Body.UpdateAppealDecisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.UpdateAppealDecisionResponse> DeptAuthUAT.Dept_AuthenticationSoap.UpdateAppealDecisionAsync(DeptAuthUAT.UpdateAppealDecisionRequest request)
        {
            return base.Channel.UpdateAppealDecisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.UpdateAppealDecisionResponse> UpdateAppealDecisionAsync(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.UpdateAppealDecisionRequest inValue = new DeptAuthUAT.UpdateAppealDecisionRequest();
            inValue.Body = new DeptAuthUAT.UpdateAppealDecisionRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).UpdateAppealDecisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.GetStringDataResponse DeptAuthUAT.Dept_AuthenticationSoap.GetStringData(DeptAuthUAT.GetStringDataRequest request)
        {
            return base.Channel.GetStringData(request);
        }
        
        public string GetStringData(string Str, string DeptCode, int Actioncode)
        {
            DeptAuthUAT.GetStringDataRequest inValue = new DeptAuthUAT.GetStringDataRequest();
            inValue.Body = new DeptAuthUAT.GetStringDataRequestBody();
            inValue.Body.Str = Str;
            inValue.Body.DeptCode = DeptCode;
            inValue.Body.Actioncode = Actioncode;
            DeptAuthUAT.GetStringDataResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).GetStringData(inValue);
            return retVal.Body.GetStringDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.GetStringDataResponse> DeptAuthUAT.Dept_AuthenticationSoap.GetStringDataAsync(DeptAuthUAT.GetStringDataRequest request)
        {
            return base.Channel.GetStringDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.GetStringDataResponse> GetStringDataAsync(string Str, string DeptCode, int Actioncode)
        {
            DeptAuthUAT.GetStringDataRequest inValue = new DeptAuthUAT.GetStringDataRequest();
            inValue.Body = new DeptAuthUAT.GetStringDataRequestBody();
            inValue.Body.Str = Str;
            inValue.Body.DeptCode = DeptCode;
            inValue.Body.Actioncode = Actioncode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).GetStringDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeptAuthUAT.AaplesarkarPayResponse DeptAuthUAT.Dept_AuthenticationSoap.AaplesarkarPay(DeptAuthUAT.AaplesarkarPayRequest request)
        {
            return base.Channel.AaplesarkarPay(request);
        }
        
        public string AaplesarkarPay(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.AaplesarkarPayRequest inValue = new DeptAuthUAT.AaplesarkarPayRequest();
            inValue.Body = new DeptAuthUAT.AaplesarkarPayRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DeptAuthUAT.AaplesarkarPayResponse retVal = ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).AaplesarkarPay(inValue);
            return retVal.Body.AaplesarkarPayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeptAuthUAT.AaplesarkarPayResponse> DeptAuthUAT.Dept_AuthenticationSoap.AaplesarkarPayAsync(DeptAuthUAT.AaplesarkarPayRequest request)
        {
            return base.Channel.AaplesarkarPayAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeptAuthUAT.AaplesarkarPayResponse> AaplesarkarPayAsync(string EncyKey, string DeptCode)
        {
            DeptAuthUAT.AaplesarkarPayRequest inValue = new DeptAuthUAT.AaplesarkarPayRequest();
            inValue.Body = new DeptAuthUAT.AaplesarkarPayRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DeptAuthUAT.Dept_AuthenticationSoap)(this)).AaplesarkarPayAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Dept_AuthenticationSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Dept_AuthenticationSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Dept_AuthenticationSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://testcitizenservices.mahaitgov.in/Dept_Authentication.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Dept_AuthenticationSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://testcitizenservices.mahaitgov.in/Dept_Authentication.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Dept_AuthenticationSoap,
            
            Dept_AuthenticationSoap12,
        }
    }
}
