//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentAuthenticationSOAPService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap")]
    public interface Dept_AuthenticationSoap
    {
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParameter", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.GetParameterResponse GetParameter(DepartmentAuthenticationSOAPService.GetParameterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParameter", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetParameterResponse> GetParameterAsync(DepartmentAuthenticationSOAPService.GetParameterRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParameterNew", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.GetParameterNewResponse GetParameterNew(DepartmentAuthenticationSOAPService.GetParameterNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParameterNew", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetParameterNewResponse> GetParameterNewAsync(DepartmentAuthenticationSOAPService.GetParameterNewRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceParameter", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.GetServiceParameterResponse GetServiceParameter(DepartmentAuthenticationSOAPService.GetServiceParameterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceParameter", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetServiceParameterResponse> GetServiceParameterAsync(DepartmentAuthenticationSOAPService.GetServiceParameterRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAppStatus", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.SetAppStatusResponse SetAppStatus(DepartmentAuthenticationSOAPService.SetAppStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAppStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.SetAppStatusResponse> SetAppStatusAsync(DepartmentAuthenticationSOAPService.SetAppStatusRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAppeal", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.InsertAppealResponse InsertAppeal(DepartmentAuthenticationSOAPService.InsertAppealRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAppeal", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.InsertAppealResponse> InsertAppealAsync(DepartmentAuthenticationSOAPService.InsertAppealRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAppealHearingDate", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.UpdateAppealHearingDateResponse UpdateAppealHearingDate(DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAppealHearingDate", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.UpdateAppealHearingDateResponse> UpdateAppealHearingDateAsync(DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAppealDecision", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.UpdateAppealDecisionResponse UpdateAppealDecision(DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAppealDecision", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.UpdateAppealDecisionResponse> UpdateAppealDecisionAsync(DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequest request);
        
        // CODEGEN: Generating message contract since element name Str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStringData", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.GetStringDataResponse GetStringData(DepartmentAuthenticationSOAPService.GetStringDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStringData", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetStringDataResponse> GetStringDataAsync(DepartmentAuthenticationSOAPService.GetStringDataRequest request);
        
        // CODEGEN: Generating message contract since element name EncyKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AaplesarkarPay", ReplyAction="*")]
        DepartmentAuthenticationSOAPService.AaplesarkarPayResponse AaplesarkarPay(DepartmentAuthenticationSOAPService.AaplesarkarPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AaplesarkarPay", ReplyAction="*")]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.AaplesarkarPayResponse> AaplesarkarPayAsync(DepartmentAuthenticationSOAPService.AaplesarkarPayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParameterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParameter", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.GetParameterRequestBody Body;
        
        public GetParameterRequest()
        {
        }
        
        public GetParameterRequest(DepartmentAuthenticationSOAPService.GetParameterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParameterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public GetParameterRequestBody()
        {
        }
        
        public GetParameterRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParameterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParameterResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.GetParameterResponseBody Body;
        
        public GetParameterResponse()
        {
        }
        
        public GetParameterResponse(DepartmentAuthenticationSOAPService.GetParameterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParameterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetParameterResult;
        
        public GetParameterResponseBody()
        {
        }
        
        public GetParameterResponseBody(string GetParameterResult)
        {
            this.GetParameterResult = GetParameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParameterNewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParameterNew", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.GetParameterNewRequestBody Body;
        
        public GetParameterNewRequest()
        {
        }
        
        public GetParameterNewRequest(DepartmentAuthenticationSOAPService.GetParameterNewRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParameterNewRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public GetParameterNewRequestBody()
        {
        }
        
        public GetParameterNewRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParameterNewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParameterNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.GetParameterNewResponseBody Body;
        
        public GetParameterNewResponse()
        {
        }
        
        public GetParameterNewResponse(DepartmentAuthenticationSOAPService.GetParameterNewResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParameterNewResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetParameterNewResult;
        
        public GetParameterNewResponseBody()
        {
        }
        
        public GetParameterNewResponseBody(string GetParameterNewResult)
        {
            this.GetParameterNewResult = GetParameterNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceParameterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceParameter", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.GetServiceParameterRequestBody Body;
        
        public GetServiceParameterRequest()
        {
        }
        
        public GetServiceParameterRequest(DepartmentAuthenticationSOAPService.GetServiceParameterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServiceParameterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public GetServiceParameterRequestBody()
        {
        }
        
        public GetServiceParameterRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceParameterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceParameterResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.GetServiceParameterResponseBody Body;
        
        public GetServiceParameterResponse()
        {
        }
        
        public GetServiceParameterResponse(DepartmentAuthenticationSOAPService.GetServiceParameterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServiceParameterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetServiceParameterResult;
        
        public GetServiceParameterResponseBody()
        {
        }
        
        public GetServiceParameterResponseBody(string GetServiceParameterResult)
        {
            this.GetServiceParameterResult = GetServiceParameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAppStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAppStatus", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.SetAppStatusRequestBody Body;
        
        public SetAppStatusRequest()
        {
        }
        
        public SetAppStatusRequest(DepartmentAuthenticationSOAPService.SetAppStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAppStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public SetAppStatusRequestBody()
        {
        }
        
        public SetAppStatusRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAppStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAppStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.SetAppStatusResponseBody Body;
        
        public SetAppStatusResponse()
        {
        }
        
        public SetAppStatusResponse(DepartmentAuthenticationSOAPService.SetAppStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAppStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetAppStatusResult;
        
        public SetAppStatusResponseBody()
        {
        }
        
        public SetAppStatusResponseBody(string SetAppStatusResult)
        {
            this.SetAppStatusResult = SetAppStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAppealRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAppeal", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.InsertAppealRequestBody Body;
        
        public InsertAppealRequest()
        {
        }
        
        public InsertAppealRequest(DepartmentAuthenticationSOAPService.InsertAppealRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAppealRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public InsertAppealRequestBody()
        {
        }
        
        public InsertAppealRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAppealResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAppealResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.InsertAppealResponseBody Body;
        
        public InsertAppealResponse()
        {
        }
        
        public InsertAppealResponse(DepartmentAuthenticationSOAPService.InsertAppealResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAppealResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertAppealResult;
        
        public InsertAppealResponseBody()
        {
        }
        
        public InsertAppealResponseBody(string InsertAppealResult)
        {
            this.InsertAppealResult = InsertAppealResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAppealHearingDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAppealHearingDate", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequestBody Body;
        
        public UpdateAppealHearingDateRequest()
        {
        }
        
        public UpdateAppealHearingDateRequest(DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAppealHearingDateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public UpdateAppealHearingDateRequestBody()
        {
        }
        
        public UpdateAppealHearingDateRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAppealHearingDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAppealHearingDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.UpdateAppealHearingDateResponseBody Body;
        
        public UpdateAppealHearingDateResponse()
        {
        }
        
        public UpdateAppealHearingDateResponse(DepartmentAuthenticationSOAPService.UpdateAppealHearingDateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAppealHearingDateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAppealHearingDateResult;
        
        public UpdateAppealHearingDateResponseBody()
        {
        }
        
        public UpdateAppealHearingDateResponseBody(string UpdateAppealHearingDateResult)
        {
            this.UpdateAppealHearingDateResult = UpdateAppealHearingDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAppealDecisionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAppealDecision", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequestBody Body;
        
        public UpdateAppealDecisionRequest()
        {
        }
        
        public UpdateAppealDecisionRequest(DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAppealDecisionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public UpdateAppealDecisionRequestBody()
        {
        }
        
        public UpdateAppealDecisionRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAppealDecisionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAppealDecisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.UpdateAppealDecisionResponseBody Body;
        
        public UpdateAppealDecisionResponse()
        {
        }
        
        public UpdateAppealDecisionResponse(DepartmentAuthenticationSOAPService.UpdateAppealDecisionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAppealDecisionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAppealDecisionResult;
        
        public UpdateAppealDecisionResponseBody()
        {
        }
        
        public UpdateAppealDecisionResponseBody(string UpdateAppealDecisionResult)
        {
            this.UpdateAppealDecisionResult = UpdateAppealDecisionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStringDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStringData", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.GetStringDataRequestBody Body;
        
        public GetStringDataRequest()
        {
        }
        
        public GetStringDataRequest(DepartmentAuthenticationSOAPService.GetStringDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStringDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Str;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Actioncode;
        
        public GetStringDataRequestBody()
        {
        }
        
        public GetStringDataRequestBody(string Str, string DeptCode, int Actioncode)
        {
            this.Str = Str;
            this.DeptCode = DeptCode;
            this.Actioncode = Actioncode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStringDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStringDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.GetStringDataResponseBody Body;
        
        public GetStringDataResponse()
        {
        }
        
        public GetStringDataResponse(DepartmentAuthenticationSOAPService.GetStringDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStringDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStringDataResult;
        
        public GetStringDataResponseBody()
        {
        }
        
        public GetStringDataResponseBody(string GetStringDataResult)
        {
            this.GetStringDataResult = GetStringDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AaplesarkarPayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AaplesarkarPay", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.AaplesarkarPayRequestBody Body;
        
        public AaplesarkarPayRequest()
        {
        }
        
        public AaplesarkarPayRequest(DepartmentAuthenticationSOAPService.AaplesarkarPayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AaplesarkarPayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncyKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeptCode;
        
        public AaplesarkarPayRequestBody()
        {
        }
        
        public AaplesarkarPayRequestBody(string EncyKey, string DeptCode)
        {
            this.EncyKey = EncyKey;
            this.DeptCode = DeptCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AaplesarkarPayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AaplesarkarPayResponse", Namespace="http://tempuri.org/", Order=0)]
        public DepartmentAuthenticationSOAPService.AaplesarkarPayResponseBody Body;
        
        public AaplesarkarPayResponse()
        {
        }
        
        public AaplesarkarPayResponse(DepartmentAuthenticationSOAPService.AaplesarkarPayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AaplesarkarPayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AaplesarkarPayResult;
        
        public AaplesarkarPayResponseBody()
        {
        }
        
        public AaplesarkarPayResponseBody(string AaplesarkarPayResult)
        {
            this.AaplesarkarPayResult = AaplesarkarPayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface Dept_AuthenticationSoapChannel : DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Dept_AuthenticationSoapClient : System.ServiceModel.ClientBase<DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap>, DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Dept_AuthenticationSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Dept_AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), Dept_AuthenticationSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Dept_AuthenticationSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Dept_AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Dept_AuthenticationSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Dept_AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Dept_AuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.GetParameterResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.GetParameter(DepartmentAuthenticationSOAPService.GetParameterRequest request)
        {
            return base.Channel.GetParameter(request);
        }
        
        public string GetParameter(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.GetParameterRequest inValue = new DepartmentAuthenticationSOAPService.GetParameterRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.GetParameterRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DepartmentAuthenticationSOAPService.GetParameterResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).GetParameter(inValue);
            return retVal.Body.GetParameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetParameterResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.GetParameterAsync(DepartmentAuthenticationSOAPService.GetParameterRequest request)
        {
            return base.Channel.GetParameterAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetParameterResponse> GetParameterAsync(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.GetParameterRequest inValue = new DepartmentAuthenticationSOAPService.GetParameterRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.GetParameterRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).GetParameterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.GetParameterNewResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.GetParameterNew(DepartmentAuthenticationSOAPService.GetParameterNewRequest request)
        {
            return base.Channel.GetParameterNew(request);
        }
        
        public string GetParameterNew(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.GetParameterNewRequest inValue = new DepartmentAuthenticationSOAPService.GetParameterNewRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.GetParameterNewRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DepartmentAuthenticationSOAPService.GetParameterNewResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).GetParameterNew(inValue);
            return retVal.Body.GetParameterNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetParameterNewResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.GetParameterNewAsync(DepartmentAuthenticationSOAPService.GetParameterNewRequest request)
        {
            return base.Channel.GetParameterNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetParameterNewResponse> GetParameterNewAsync(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.GetParameterNewRequest inValue = new DepartmentAuthenticationSOAPService.GetParameterNewRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.GetParameterNewRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).GetParameterNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.GetServiceParameterResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.GetServiceParameter(DepartmentAuthenticationSOAPService.GetServiceParameterRequest request)
        {
            return base.Channel.GetServiceParameter(request);
        }
        
        public string GetServiceParameter(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.GetServiceParameterRequest inValue = new DepartmentAuthenticationSOAPService.GetServiceParameterRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.GetServiceParameterRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DepartmentAuthenticationSOAPService.GetServiceParameterResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).GetServiceParameter(inValue);
            return retVal.Body.GetServiceParameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetServiceParameterResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.GetServiceParameterAsync(DepartmentAuthenticationSOAPService.GetServiceParameterRequest request)
        {
            return base.Channel.GetServiceParameterAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetServiceParameterResponse> GetServiceParameterAsync(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.GetServiceParameterRequest inValue = new DepartmentAuthenticationSOAPService.GetServiceParameterRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.GetServiceParameterRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).GetServiceParameterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.SetAppStatusResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.SetAppStatus(DepartmentAuthenticationSOAPService.SetAppStatusRequest request)
        {
            return base.Channel.SetAppStatus(request);
        }
        
        public string SetAppStatus(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.SetAppStatusRequest inValue = new DepartmentAuthenticationSOAPService.SetAppStatusRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.SetAppStatusRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DepartmentAuthenticationSOAPService.SetAppStatusResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).SetAppStatus(inValue);
            return retVal.Body.SetAppStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.SetAppStatusResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.SetAppStatusAsync(DepartmentAuthenticationSOAPService.SetAppStatusRequest request)
        {
            return base.Channel.SetAppStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.SetAppStatusResponse> SetAppStatusAsync(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.SetAppStatusRequest inValue = new DepartmentAuthenticationSOAPService.SetAppStatusRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.SetAppStatusRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).SetAppStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.InsertAppealResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.InsertAppeal(DepartmentAuthenticationSOAPService.InsertAppealRequest request)
        {
            return base.Channel.InsertAppeal(request);
        }
        
        public string InsertAppeal(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.InsertAppealRequest inValue = new DepartmentAuthenticationSOAPService.InsertAppealRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.InsertAppealRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DepartmentAuthenticationSOAPService.InsertAppealResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).InsertAppeal(inValue);
            return retVal.Body.InsertAppealResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.InsertAppealResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.InsertAppealAsync(DepartmentAuthenticationSOAPService.InsertAppealRequest request)
        {
            return base.Channel.InsertAppealAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.InsertAppealResponse> InsertAppealAsync(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.InsertAppealRequest inValue = new DepartmentAuthenticationSOAPService.InsertAppealRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.InsertAppealRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).InsertAppealAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.UpdateAppealHearingDateResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.UpdateAppealHearingDate(DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequest request)
        {
            return base.Channel.UpdateAppealHearingDate(request);
        }
        
        public string UpdateAppealHearingDate(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequest inValue = new DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DepartmentAuthenticationSOAPService.UpdateAppealHearingDateResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).UpdateAppealHearingDate(inValue);
            return retVal.Body.UpdateAppealHearingDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.UpdateAppealHearingDateResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.UpdateAppealHearingDateAsync(DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequest request)
        {
            return base.Channel.UpdateAppealHearingDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.UpdateAppealHearingDateResponse> UpdateAppealHearingDateAsync(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequest inValue = new DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.UpdateAppealHearingDateRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).UpdateAppealHearingDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.UpdateAppealDecisionResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.UpdateAppealDecision(DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequest request)
        {
            return base.Channel.UpdateAppealDecision(request);
        }
        
        public string UpdateAppealDecision(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequest inValue = new DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DepartmentAuthenticationSOAPService.UpdateAppealDecisionResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).UpdateAppealDecision(inValue);
            return retVal.Body.UpdateAppealDecisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.UpdateAppealDecisionResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.UpdateAppealDecisionAsync(DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequest request)
        {
            return base.Channel.UpdateAppealDecisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.UpdateAppealDecisionResponse> UpdateAppealDecisionAsync(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequest inValue = new DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.UpdateAppealDecisionRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).UpdateAppealDecisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.GetStringDataResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.GetStringData(DepartmentAuthenticationSOAPService.GetStringDataRequest request)
        {
            return base.Channel.GetStringData(request);
        }
        
        public string GetStringData(string Str, string DeptCode, int Actioncode)
        {
            DepartmentAuthenticationSOAPService.GetStringDataRequest inValue = new DepartmentAuthenticationSOAPService.GetStringDataRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.GetStringDataRequestBody();
            inValue.Body.Str = Str;
            inValue.Body.DeptCode = DeptCode;
            inValue.Body.Actioncode = Actioncode;
            DepartmentAuthenticationSOAPService.GetStringDataResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).GetStringData(inValue);
            return retVal.Body.GetStringDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetStringDataResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.GetStringDataAsync(DepartmentAuthenticationSOAPService.GetStringDataRequest request)
        {
            return base.Channel.GetStringDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.GetStringDataResponse> GetStringDataAsync(string Str, string DeptCode, int Actioncode)
        {
            DepartmentAuthenticationSOAPService.GetStringDataRequest inValue = new DepartmentAuthenticationSOAPService.GetStringDataRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.GetStringDataRequestBody();
            inValue.Body.Str = Str;
            inValue.Body.DeptCode = DeptCode;
            inValue.Body.Actioncode = Actioncode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).GetStringDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DepartmentAuthenticationSOAPService.AaplesarkarPayResponse DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.AaplesarkarPay(DepartmentAuthenticationSOAPService.AaplesarkarPayRequest request)
        {
            return base.Channel.AaplesarkarPay(request);
        }
        
        public string AaplesarkarPay(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.AaplesarkarPayRequest inValue = new DepartmentAuthenticationSOAPService.AaplesarkarPayRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.AaplesarkarPayRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            DepartmentAuthenticationSOAPService.AaplesarkarPayResponse retVal = ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).AaplesarkarPay(inValue);
            return retVal.Body.AaplesarkarPayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.AaplesarkarPayResponse> DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap.AaplesarkarPayAsync(DepartmentAuthenticationSOAPService.AaplesarkarPayRequest request)
        {
            return base.Channel.AaplesarkarPayAsync(request);
        }
        
        public System.Threading.Tasks.Task<DepartmentAuthenticationSOAPService.AaplesarkarPayResponse> AaplesarkarPayAsync(string EncyKey, string DeptCode)
        {
            DepartmentAuthenticationSOAPService.AaplesarkarPayRequest inValue = new DepartmentAuthenticationSOAPService.AaplesarkarPayRequest();
            inValue.Body = new DepartmentAuthenticationSOAPService.AaplesarkarPayRequestBody();
            inValue.Body.EncyKey = EncyKey;
            inValue.Body.DeptCode = DeptCode;
            return ((DepartmentAuthenticationSOAPService.Dept_AuthenticationSoap)(this)).AaplesarkarPayAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Dept_AuthenticationSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Dept_AuthenticationSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Dept_AuthenticationSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://aaplesarkar.mahaonline.gov.in/Dept_Authentication.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Dept_AuthenticationSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://aaplesarkar.mahaonline.gov.in/Dept_Authentication.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Dept_AuthenticationSoap,
            
            Dept_AuthenticationSoap12,
        }
    }
}
